config/routes.rb
TaskManager::Application.routes.draw do

  get "sessions/new"

	resources :users

	resources :progects do
		resources :tasks
	end

	root :to => 'progects#index'

  get 'tasks/up_priority/:id'   => 'tasks#up_priority'
	get 'tasks/down_priority/:id' => 'tasks#down_priority'
  post 'tasks/add/:progect_id'           => 'tasks#add'
	resources :sessions, :only => [:new, :create, :destroy]
	match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/progect.rb
class Progect < ActiveRecord::Base
  attr_accessible :name

	validates :name, :presence=>true, :length => {:maximum=> 50}
	has_many :tasks, :dependent => :destroy

end

app/models/status.rb
class Status < ActiveRecord::Base
  # attr_accessible :title, :body
	has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :description, :priority, :deadline

	validates :name, :presence=>true, :length => {:maximum=> 50}
  validates :description,  :length => {:maximum=> 250}

	belongs_to :progect
	belongs_to :status

	def add_priority(step)
	 self.priority += step;
	end

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor   :password
  attr_accessible :email, :name, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, :presence=>true, :length => {:maximum=> 50}
	validates :email, :presence=>true, :format => {:with => email_regex}, :uniqueness => true
	validates :password, :presence=>true, :confirmation => true, :length   => { :maximum => 50 }

	before_save :enscrypt_password

	def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

 	def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

	def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

	private

	def enscrypt_password
		self.salt = make_salt if new_record?
		self.encrypted_password = encrypt(password)
	end

	def encrypt(string)
		secure_hash("#{salt}--#{string}")
	end

	def make_salt
	secure_hash("#{Time.now.utc}--#{password}")
	end

	def secure_hash(string)
  Digest::SHA2.hexdigest(string)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/progects_controller.rb
class ProgectsController < ApplicationController
   before_filter :authenticate, :only => [:edit, :update,  :destroy, :new, :index]

  def new
		@progect = Progect.new
  end

  def create
		@progect = Progect.new(params[:progect])
  		if @progect.save
  			redirect_to :root
			else
				render "new"
			end
  end

	def index
  	@progects = Progect.all
	end

	def edit
		@progect = Progect.find(params[:id])
	end

	def	update
		@progect = Progect.find(params[:id])
		if @progect.update_attributes(params[:progect])
		redirect_to :root
		else
		render "edit"
		end
	end

  def destroy
  	@progect = Progect.find(params[:id])
		@progect.destroy
			respond_to do |format|
				format.html {redirect_to :root}
				format.js
				end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
		  user = User.authenticate(params[:session][:email],
                           params[:session][:password])
  	 if user.nil?
    		flash.now[:error] = "Invalid email/password combination."
        @title = "Sign in"
        render 'new'
 	   else
   		sign_in user
			redirect_to user
 		 end
	end

	def destroy
		sign_out
    redirect_to root_path
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
 before_filter :authenticate, :only => [:new, :show, :add, :edit, :destroy,:update, :create, :up_priority,  :down_priority]
  def new
		@progect = Progect.find(params[:progect_id])
		@task = @progect.tasks.build
  end

	def show
	@progect = Progect.find(params[:progect_id])
	@task    = @progect.tasks.find(params[:id])
	end

	def add
		@progect = Progect.find(params[:progect_id])
      @task  = @progect.tasks.new(:name =>params[:name])
			if @task.save
				flash[:Add] =  @task.name
    	else
					@task.errors.full_messages.each do |msg|
						flash[:error] = msg
					end
			end
			respond_to do |format|
			format.html {redirect_to :root}
			format.js
			end
	end

  def edit
	@progect = Progect.find(params[:progect_id])
	@task    = @progect.tasks.find(params[:id])
  end

  def destroy
    @progect = Progect.find(params[:progect_id])
		@task = @progect.tasks.find(params[:id])
		@task.delete
		respond_to do |format|
			format.html {redirect_to :root}
			format.js
		end
  end

  def update
		@progect = Progect.find(params[:progect_id])
		@task = @progect.tasks.find(params[:id])
		if @task.update_attributes(params[:task])
			redirect_to :root
		else
			render "edit"
		end
  end

	def up_priority
		@tasks = Task.find (params[:id])
		@tasks.add_priority(1)
  	@tasks.save
		redirect_to :root
	end

	def down_priority
		@tasks = Task.find (params[:id])
		@tasks.add_priority(-1)
		@tasks.save
		redirect_to :root
	end

	def create
		@progect = Progect.find(params[:progect_id])
		@task = @progect.tasks.new(params[:task])
		if @task.save
			respond_to do |format|
				format.html {redirect_to :root}
				format.js
			end
		else
			render "new"
		end
	end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_filter :authenticate, :only => [:edit, :update]

def show
		 @user = User.find(params[:id])
  end

  def new
		@user = User.new
  end

	def create
		@user = User.new(params[:user])
		if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
			redirect_to @user
		else
			render "new"
		end
	end

	def edit
    @user = User.find(params[:id])
    @title = "Edit user"
  end

	def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/progect_helper.rb
module ProgectHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

	def signed_in?
    !current_user.nil?
  end

	def sign_out
    cookies.delete(:remember_token)
   @current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

	 def authenticate
    deny_access unless signed_in?
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

  private

  def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
  end

  def remember_token
      cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_header.html.erb
<header>

  <nav class="round">
    <ul class  = "inlinelist">
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
	<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div id = "content">
  <% flash.each do |key, value| %>
          <div class="flash"><%=value %></div>
  <% end %>
<%= yield %>
<!--<%= debug params %>-->
<!--<%= debug flash %>-->
</div>

</body>
</html>

app/views/progects/_form.html.erb
<% if @progect.errors.any? %>
		<% @model = @progect %>
	  <%= render 'shared/error_messages' %>
		<% end %>
<%= form_for @progect do |p| %>
<%=p.text_field :name %>
<%=p.submit %>
<%=link_to "Back", progects_path %>
<% end %>

app/views/progects/_progects.html.erb
<%= content_tag_for(:table, @progects) do |p| %>


<tr class="head_tr">
<td></td>

<td><h1><%= p.name %></h1></td>

<td><%=link_to  edit_progect_path(p), :class => "icon_link" do %>  <i class = "foundicon-edit"></i> <% end %>
<%=link_to  progect_path(p), :confirm => "Your are sure?", :method=> :delete, :remote => true, :class => "icon_link" do %>
<i class = "foundicon-remove"></i>
<% end %>

<tr class="add_tr">
<td><%= link_to new_progect_task_path(p) do  %>
<i class = "foundicon-add-doc"></i> <% end %> </td>

<td><%= form_tag url_for(:action=>"add",:controller=>"tasks", :progect_id => p.id, :class => "add_task"), :remote => true  do %>
<%=text_field_tag (:name) %></td>

<td><%=submit_tag("Add",:class => "add_button")  %></td>
<% end %>
</tr>

<% p.tasks.order("priority DESC").each do |task| %>

<%= render :partial => "tasks/task", :locals => { :p => p, :task => task } %>
<% end %>

<% end %>

app/views/progects/create.html.erb
<h1>Progect#create</h1>

app/views/progects/destroy.js.erb
$('#<%= dom_id(@progect) %>').hide();

app/views/progects/edit.html.erb
<h1> Edit progect </h1>
<%= render "form" %>

app/views/progects/index.html.erb
<%= render "progects" %>


<div>
<%=link_to "New progect", new_progect_path, :class =>"new_progect_button" %>
</div>

app/views/progects/new.html.erb
<h1>Add new progect:</h1>
<%= render "form" %>

app/views/shared/_error_messages.html.erb
<div id="error_explanation">
<h2><%= pluralize(@model.errors.count, "error") %>
       from being saved:</h2>

<ul>
    <% @model.errors.full_messages.each do |msg| %>
      <li><%=msg %></li>
    <% end %>
</ul>
</div>

app/views/tasks/_form.html.erb
	<% if @task.errors.any? %>
		<% @model = @task %>
	  <%= render 'shared/error_messages' %>
	<% end %>

<%= form_for [@progect, @task] do |t| %>

<%=t.label :name %></br>
<%=t.text_field :name %> </br>

<%=t.label :description %></br>
<%=t.text_area :description, :rows=>5 %></br>

<%=t.label :priority %>
<%=t.text_field :priority %> <br>

<%=t.label :deadline %>
<%=t.date_select :deadline %></br>
<%=t.submit %>
<%=link_to "back", progects_path %>
<% end %>

app/views/tasks/_task.html.erb
<%= content_tag_for(:tr, task,:class => "task_tr") do |t| %>
<td><%=link_to  [p,t], :class => "icon_link" do %> <i class = "foundicon-folder"></i> <% end %></td>
<td><%= t.name %></td>

<td>
<%= link_to  edit_progect_task_path(p,t), :class => "icon_link" do %>
<i class = "foundicon-edit"></i> <% end %>
<%= link_to  progect_task_path(p,t), :method=>"delete", :confirm=>"Are you sure", :class => "icon_link", :remote => true do %>
<i class = "foundicon-remove"></i> <% end %>

<%= link_to raw('<i class = "foundicon-up-arrow"></i>') , { :action => "up_priority", :controller =>"tasks", :id=> t.id}, :class => "icon_link" %>
<%= link_to raw('<i class = "foundicon-down-arrow"></i>'), {:action => "down_priority", :controller =>"tasks", :id=> t.id}, :class => "icon_link" %></td>
</td>
<% end %>

app/views/tasks/add.js.erb
$('#<%= dom_id(@progect) %>').append('<%= escape_javascript(render :partial => "tasks/task", :locals => { :p => @progect, :task => @task } ) %>');

app/views/tasks/delete.html.erb
<h1>Task#delete</h1>
<p>Find me in app/views/task/delete.html.erb</p>

app/views/tasks/destroy.js.erb
$('#<%= dom_id(@task) %>').css("background", "red");
$('#<%= dom_id(@task) %>').hide(1000);

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "form" %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render "form" %>

app/views/tasks/show.html.erb
<p>Name:<%= @task.name %></p><br>
<p>Description:<%= @task.description %></p>
<p>priority:<%= @task.priority %>
<p>deadline: <%= @task.deadline %></p>
<%=link_to "back", progects_path %>
<%=link_to "edit", edit_progect_task_path(@progect, @task) %>

app/views/tasks/update.html.erb
<h1>Task#update</h1>
<p>Find me in app/views/task/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
		<% @model = @user %>
	  <%= render 'shared/error_messages' %>
		<% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>